apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-application
  namespace: argocd
spec:
  project: lab-kube

  source:
    repoURL: https://github.com/douglasdalves/lab-argocd.git
    targetRevision: main
    path: /
  destination: 
    server: https://kubernetes.default.svc
    namespace: lab-hml

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
